<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class RedirectController extends Controller
{
    public function index($redirect)
    {
        return call_user_func([new self(), $redirect]);
    }

    public function contest()
    {
        $redirect = 'http://mp.weixin.qq.com/s?__biz=MzUyODAwOTAzNA==&mid=100000312&idx=1&sn=9f82c2c04f2d45d7d562e319ce14a99d&chksm=7a77901d4d00190b25df013cf47b6f56efafe2cfe2afc28e9bfe0630c34f5b628c6132a18871#rd';
        return view('redirect.contest', compact('redirect'));
    }

    public function __call($method, $parameters)
    {
        abort(404);
        parent::__call($method, $parameters); // TODO: Change the autogenerated stub
    }
}
